# Site settings
title:       叶剑烨的个人注释
email:       yejianye@gmail.com
author:      叶剑烨
description: "停顿十秒钟，思考沉淀"
baseurl:     ""
url:         "http://www.yejianye.com"
date_format: "%b %-d, %Y"

# Google services
google_analytics:
google_verification:

# Baidu
baidu_verification: bOzpMmOb88
baidu_analytics: a328f152ad53a33a042999efdd3de235

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    true
show_social_icons:    false
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: 

# Social icons
github_username: yejianye
bitbucket_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: '分享到'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
# redcarpet:
#   extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
plugins:
  - jekyll-sitemap
  - jekyll-paginate
